### PR TITLE
Fixed Bug With Executing Git From Path With Spaces

### LINKED ISSUE #33: Git Exe Path Doesn't Handle Spaces
[A user in the Discord](https://discord.com/channels/570292611215130634/804374967714054144/1036305682183491714) reported that they were having trouble passing the 'Open Source: Configuring Git' objective. Based on the error they were getting, it looks like an issue with the git.exe being called via a path that has spaces with no surrounding quotes (which @rmkubik pointed out in the [following response(s)](https://discord.com/channels/570292611215130634/804374967714054144/1036314675605930065))
image

### PR DESCRIPTION
**Pull request by MarvelProgramming**
-Added quotes around the path that the "exec" function uses when searching for the Git executable

For issue #33

### CODE REVIEW

File: scripts/objectiveValidation.js [hunk 1]
```diff
@@ -10,7 +10,7 @@ async function execGitWithArgs(helper, argString, execOptions = {}) {
     );
   }
 
-  return exec(`${TQ_GIT_EXE} ${argString}`, execOptions);
```
Comment (rmkubik) [inline scripts/objectiveValidation.js:13]: Let's add a check before this for leading and trailing `"` and `'` in the TQ_GIT_EXE env var contents.

We should throw a new error if these exist with a message:
> TwilioQuest no longer requires you to surround your git executable path with quotation marks if it contains spaces.

Let's also put a comment to say that we advised users to add quotations marks to get past this validator after the TQ 3.10.0 release introduced the bug.

**Review by rmkubik — CHANGES_REQUESTED** [review]

**Comment by alvinphilips** [comment]
Hi, I was just going through this myself. Would escaping the spaces (by prepending the spaces with `\\`) instead be a cleaner approach? I think it may also eliminate the need to throw an Error if a user does include the quotation marks.

**Comment by MarvelProgramming** [comment]
> Hi, I was just going through this myself. Would escaping the spaces (by prepending the spaces with `\\`) instead be a cleaner approach? I think it may also eliminate the need to throw an Error if a user does include the quotation marks.

Correct me if I'm wrong, but I don't think this works on Windows? I tested it in PowerShell and got an `InvalidArgument` error

**Review by rmkubik — APPROVED** [review]
